services:
  auth-service:
    ports:
      - "3001:3001"

  media-service:
    ports:
      - "3002:3002"

  chat-service:
    ports:
      - "3003:3003"

  auth-db:
    ports:
      - "5433:5432"

  auth-redis:
    ports:
      - "6379:6379"

  chat-db:
    ports:
      - "5434:5432"
