events {}

http {
  upstream auth_service {
    server auth-service:3001;
  }

  server {
    listen 80;

    location /health {
      return 200 "gateway is healthy\n";
      add_header Content-Type text/plain;
    }

    location /auth/ {
      proxy_pass http://auth_service/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/auth/ {
      proxy_pass http://auth_service/admin/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}